### PR TITLE
WIP: Add list helper

### PR DESCRIPTION
**Pull request by jvanbruegge**
To make handling lists easier #28 . Should work for 99% of use cases.
Usage:
```js
function main(sources) {
    const childrenSinks = List(s => s.myArray, ChildComponent)(sources)
    ...
}
```
I think this would be nice to have

### CODE REVIEW

**Comment by staltz** [comment]
@jvanbruegge I'm worried about the Cycle DOM dependency here, because then this library isn't anymore doing just one concern. Couldn't this `List` helper be published separately, perhaps in a helpers library like Ramda or Lodash style?

**Comment by jvanbruegge** [comment]
I could include it in `cyclejs-utils` or publish it seperately. The other option would be to remove the dom dependency by either making the wrapper not optional or by manually creating a vnode with selector and children.

**Comment by staltz** [comment]
@jvanbruegge With a manual vnode creation there is still mixing of *concerns*, where this library has some influence over DOM purposes, besides just influence over state management.

**Comment by jvanbruegge** [comment]
Plus it's not a very clean solution. I would make it required, is the easiest solution

**Comment by kylecordes** [comment]
It seems reasonable for me for the consuming application to provide whatever VDOM wrapping function makes the most sense in context. Sometimes that might be a div, other times a ul, ol, etc. It doesn't feel that important to me, to have it default to div.

**Comment by jvanbruegge** [comment]
So, cleaned it up

**Comment by jvanbruegge** [comment]
@milankinen's solution is much cleaner

**Pull request closed without merging**
