### PR TITLE
Emit state changes using microtask queue

### PR DESCRIPTION
**Pull request by ntilwalli**
Resolves https://github.com/staltz/cycle-onionify/issues/61

### CODE REVIEW

**Comment by ntilwalli** [comment]
@staltz I have a branch with the requested buffer change, but it doesn't seem necessary.  The change can be viewed here (with code demoing the buffer and no-buffer options): 

https://github.com/ntilwalli/cycle-onionify/blob/763d59a79b1322d6b272853d7af54fc13abf6b65/src/onionify.ts#L66

What does the buffer accomplish?  By my understanding, the microtask queue does all the necessary work by itself.  If onionify subscribes to the reducer$ before a component has subscribed to the state$ and the reducer$ sees immediate synchronous emissions that get imitated directly (no buffer) via the microtask queue, it should work fine.  By the time the queued microtask is called (and the proxy checks if there are any subscribers) they should exist, because by that point the full event loop turn would have completed.  In what scenario is that not a complete solution to the ordering problem?

**Comment by ntilwalli** [comment]
Related... I just removed buffering from `@cycle/run`, and only kept the microtask scheduling and it passed all tests across the whole project.  What am I missing?

My fork of cyclejs without run buffering: https://github.com/ntilwalli/cyclejs/

**Comment by ntilwalli** [comment]
@staltz any thoughts?

**Comment by staltz** [comment]
@ntilwalli I'm thinking that this is a cycle/run issue and I've been thinking a lot what to do overall: how to make (or not) onionify a plugin that uses cycle/run, and where to build the microtask scheduling, or whether we need a stream library with a good default scheduler (like RxJS 4 was). This is a lot of big decisions so I don't want to do it hastily, forgive me if it seems like this PR was being put aside.

**Comment by ntilwalli** [comment]
@staltz Thanks for the response.  No worries.  My point (which is independent of the broader points you're considering) was that the buffering seems redundant.  Microtask scheduling already works using a queue under the hood so the buffering that cycle/run is doing is unnecessary.  Scheduling a microtask inherently buffers it.  That's the point of the example I posted.  The behaviour of the cycle test suite is the same with or without the manual buffering and I believe you can remove it.  The microtask queue does all the work for you.

I'd also like to note that making onionify a plugin means it will bypass cycle/run and will not get the benefit of whatever async work you commit to doing in cycle/run (scheduling, microtask or both).  Any pure-plugin in the proposed architecture will need to manage scheduling for itself.

**Comment by staltz** [comment]
@ntilwalli Yes I agree fully with your first paragraph. It surprised me that we don't need the buffering in cycle/run, that's what led me to think bigger picture and try to understand the problem. I don't want these sync race conditions bugs coming up again so I want to get it right once and for all.

About your second paragraph, I think you misunderstood what plugins will be, because onionify as a plugin would certainly use cycle/run scheduling.

**Comment by ntilwalli** [comment]
Ah, yes I had misunderstood.  I see in the proposed arch diagram that all sink emissions will pass through cycle/run in the new model.

**Comment by ntilwalli** [comment]
If I update the PR to use the microtask scheduler without the manual buffering would that be mergeable?

**Comment by staltz** [comment]
You mean this PR? It doesn't have buffering here. Oh and by the way I released that microtask file as its own package, `quicktask` on npm. Lets use that instead of copy pasting.

**Comment by staltz** [comment]
I'll do the `quicktask` inclusion after merging your PR. Thanks @ntilwalli!

**Pull request merged**
