### PR TITLE
Fix infinite update loop in collection

### PR DESCRIPTION
**Pull request by abaco**
Another issue from `collection` #28:

> it's a bit fragile because it's easy to put the program in an infinite loop if you create a new state object that has the same deep contents as the previous state object

My fix seems to work, but I have to write a test or at least a minimal example.

Basically when the collection item gets a state update from the parent, it doesn't send it back again to the parent as a reducer. This is enough to break the infinite loop.

### CODE REVIEW

**Comment by abaco** [comment]
@staltz are there any side effects to @milankinen solution? I can see none.

**Comment by staltz** [comment]
Yeah, onionifyChild was used to keep the state update local to the child, but I guess the bottleneck, if any, is pickCombine/pickMerge of some sinks, not state updates. The side effect is that some tests don't pass but it's simple stuff, I can fix myself.

**Comment by staltz** [comment]
Well actually this important test broke https://github.com/staltz/cycle-onionify/blob/collection/test.js#L577 and it seems defaultReducers for inserted components aren't being applied.

**Comment by abaco** [comment]
**Sorry** @staltz, this PR created more work than it saved... All tests run with only the first commit dd226b59c865cdb00709179eb9a5a9f25576b884, maybe it's easier to just include that.

**Comment by staltz** [comment]
Yeah, that sounds good to me. Can you make another PR with that commit? It would be actually nice to remove onionifyChild entirely, but we need correctness first.

**Pull request merged**
