### PR TITLE
Add support for scopeGenerators for asCollection

### PR DESCRIPTION
**Pull request by ntilwalli**
Currently `asCollection` does not work with `cyclejs-sortable` since it requires sibling isolation and `asCollection` only supports default isolation scopes for sources/sinks (in the case of DOM, total isolation).  This PR modifies the `asCollection` API to take an optional `options` parameter which can contain both the `getKey` option and/or a `scopeGenerators` option which allows the user to customize the isolation scope for a given sources/sink.

An example usage can be seen in the `List` component posted in the `examples/sortable` directory.

### CODE REVIEW

**Comment by abaco** [comment]
An alternative solution to the problem with `sortable` would be to have `asCollection` do sibling isolation instead of full isolation. Would that cause other problems? I'm not sure, but I don't think so.

In any case it's just an idea, I'd be also happy with the `options` object.

**Comment by jvanbruegge** [comment]
It would, but other use cases may require different or no isolation, I think options is best

**Comment by jvanbruegge** [comment]
Btw, can you change the target brabch from master to collection?

**Comment by staltz** [comment]
> An alternative solution to the problem with sortable would be to have asCollection do sibling isolation instead of full isolation. Would that cause other problems? I'm not sure, but I don't think so.

It would cause problems just like in other cases, total isolation should be default and sibling isolation should be opt-in. The basic counterexample to sibling isolation is you usually dont want `domSource.select('.btn')` in the parent component to select btn elements in the children, unless you *explicitly* want to.

**Pull request closed without merging**
