### PR TITLE
WIP: Collection source

### PR DESCRIPTION
**Pull request by jvanbruegge**
This is the `pick` implementation of @milankinen

TODO:
- [ ] cleanup
- [ ] catchall operation (`pick({ DOM: 'combine', '*': 'merge' })`)
- [ ] discuss the approach

### CODE REVIEW

**Comment by abaco** [comment]
Wow, that's a lot of stuff for one PR. At a quick glance there seem to be optimizations, new examples, and API changes. In general there shouldn't be much to discuss about optimizations, if they work they should be accepted. But what API changes are being proposed, exactly? Would you guys be so kind as to summarize them?

**Comment by jvanbruegge** [comment]
I'm currently redoing this as this is changing a lot more than needed. The core idea is not to expose the instance stream, but provide a method for getting the sinks object (combined&merged) directly.

**Comment by staltz** [comment]
@abaco
> Wow, that's a lot of stuff for one PR.

Yeah, too much and it makes it too hard to merge, and harder to justify each change. The main idea is what Jan highlighted:

> The core idea is not to expose the instance stream, but provide a method for getting the sinks object (combined&merged) directly.

I think it's a good idea to avoid exposing the instances data structure, it would satisfy a goal that @abaco well expressed in issue #28:

> (We should try to) Keep the weirdness of `collection` as localized as possible.

But the actual `pick` API could have better naming (`pick` in the current stable version means just a way of selecting *one* sink from all instances, this API is doing both pick **and** mix and also returning the sinks object for a collection) and encoding the operators as strings is very alien to the Cycle.js ecosystem, would probably cause a disturbance in https://en.wikipedia.org/wiki/Principle_of_least_astonishment.

When it comes to API proposals and designs, we need to test them in the wild before jumping to the conclusion. I already rewrote examples and my projects to onionify-collection, and it works nicely, but I think what matters most is how beginners are going to understand the API, and how fast they acquire that understanding.

I'll make it a checklist task in #28 to ask at least one or two beginners or common Cycle users to try out the onionify-collection API. If it fits like a glove to them, we can release it as it is, and then later figure out how to hide the instances data structure in a (hopefully) non-breaking change release, after having discussed API design together.

**Comment by jvanbruegge** [comment]
Closing this for now, as the cire was merged

**Pull request closed without merging**
